package com.telcobright.splitverse.examples.entity;

import com.telcobright.core.entity.ShardingEntity;
import com.telcobright.core.annotation.*;

import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * Telecom subscriber entity for Split-Verse demonstration.
 * 
 * Key characteristics:
 * - String ID (externally generated - NO AUTO_INCREMENT)
 * - Supports various telecom identifiers (MSISDN, IMSI, ICCID)
 * - Sharded by creation date for time-based partitioning
 */
@Table(name = "subscribers")
public class SubscriberEntity implements ShardingEntity {
    
    @Id(autoGenerated = false)  // CRITICAL for Split-Verse: IDs are generated externally
    @Column(name = "subscriber_id")
    private String id;  // Externally generated (NanoID, ULID, etc.)
    
    @Index(name = "idx_msisdn")
    @Column(name = "msisdn", nullable = false)
    private String msisdn;  // Phone number (e.g., +8801712345678)
    
    @Column(name = "imsi")
    private String imsi;  // International Mobile Subscriber Identity
    
    @Column(name = "iccid")
    private String iccid;  // SIM card serial number
    
    @Column(name = "balance")
    private BigDecimal balance;
    
    @Column(name = "status")
    private String status;  // ACTIVE, SUSPENDED, TERMINATED
    
    @Column(name = "plan_type")
    private String plan;  // PREPAID, POSTPAID
    
    @Column(name = "data_balance_mb")
    private Long dataBalanceMb;
    
    @Column(name = "voice_balance_minutes")
    private Integer voiceBalanceMinutes;
    
    @ShardingKey
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
    
    @Column(name = "last_activity")
    private LocalDateTime lastActivity;
    
    @Column(name = "activated_at")
    private LocalDateTime activatedAt;
    
    // Constructors
    public SubscriberEntity() {}
    
    public SubscriberEntity(String id, String msisdn, BigDecimal balance, 
                           String status, LocalDateTime createdAt) {
        this.id = id;
        this.msisdn = msisdn;
        this.balance = balance;
        this.status = status;
        this.createdAt = createdAt;
    }
    
    // Getters and Setters
    public String getId() { return id; }
    
    public void setId(String id) { this.id = id; }
    
    public LocalDateTime getCreatedAt() { return createdAt; }
    
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
    
    public String getMsisdn() { return msisdn; }
    public void setMsisdn(String msisdn) { this.msisdn = msisdn; }
    
    public String getImsi() { return imsi; }
    public void setImsi(String imsi) { this.imsi = imsi; }
    
    public String getIccid() { return iccid; }
    public void setIccid(String iccid) { this.iccid = iccid; }
    
    public BigDecimal getBalance() { return balance; }
    public void setBalance(BigDecimal balance) { this.balance = balance; }
    
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    
    public String getPlan() { return plan; }
    public void setPlan(String plan) { this.plan = plan; }
    
    public Long getDataBalanceMb() { return dataBalanceMb; }
    public void setDataBalanceMb(Long dataBalanceMb) { this.dataBalanceMb = dataBalanceMb; }
    
    public Integer getVoiceBalanceMinutes() { return voiceBalanceMinutes; }
    public void setVoiceBalanceMinutes(Integer voiceBalanceMinutes) { 
        this.voiceBalanceMinutes = voiceBalanceMinutes; 
    }
    
    public LocalDateTime getLastActivity() { return lastActivity; }
    public void setLastActivity(LocalDateTime lastActivity) { this.lastActivity = lastActivity; }
    
    public LocalDateTime getActivatedAt() { return activatedAt; }
    public void setActivatedAt(LocalDateTime activatedAt) { this.activatedAt = activatedAt; }
    
    @Override
    public String toString() {
        return String.format("Subscriber{id='%s', msisdn='%s', balance=%s, status='%s', plan='%s'}",
            id, msisdn, balance, status, plan);
    }
}