package com.telcobright.examples.entity;

import com.telcobright.core.entity.ShardingEntity;

import com.telcobright.core.annotation.*;
import java.time.LocalDateTime;

/**
 * Citizen entity for government record management
 * Uses single partitioned table strategy with MySQL native partitioning
 * Partitions by date range: p20250803, p20250804, etc.
 * IDs are externally generated strings (NO AUTO_INCREMENT)
 */
@Table(name = "citizens")
public class CitizenEntity implements ShardingEntity<LocalDateTime> {
    
    @Id(autoGenerated = false)  // Externally generated ID
    @Column(name = "id")
    private String id;
    
    @Column(name = "first_name", nullable = false)
    private String firstName;
    
    @Column(name = "last_name", nullable = false)
    private String lastName;
    
    @Column(name = "date_of_birth", nullable = false)
    private String dateOfBirth; // YYYY-MM-DD format
    
    @Column(name = "social_security_number", nullable = false)
    private String socialSecurityNumber;
    
    @Column(name = "email")
    private String email;
    
    @Column(name = "phone_number")
    private String phoneNumber;
    
    @Column(name = "address")
    private String address;
    
    @Column(name = "status", nullable = false)
    private String status; // ACTIVE, INACTIVE, SUSPENDED, PENDING, VERIFIED
    
    @ShardingKey
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;
    
    @Column(name = "updated_at")
    private LocalDateTime updatedAt;
    
    // Constructors
    public CitizenEntity() {}
    
    public CitizenEntity(String firstName, String lastName, String dateOfBirth, 
                        String socialSecurityNumber, String email, String phoneNumber,
                        String address, String status, LocalDateTime createdAt) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.dateOfBirth = dateOfBirth;
        this.socialSecurityNumber = socialSecurityNumber;
        this.email = email;
        this.phoneNumber = phoneNumber;
        this.address = address;
        this.status = status;
        this.createdAt = createdAt;
    }
    
    public CitizenEntity(String firstName, String lastName, String dateOfBirth, 
                        String socialSecurityNumber, String email, String phoneNumber,
                        String address, String status, LocalDateTime createdAt, 
                        LocalDateTime updatedAt) {
        this(firstName, lastName, dateOfBirth, socialSecurityNumber, email, 
             phoneNumber, address, status, createdAt);
        this.updatedAt = updatedAt;
    }
    
    // Getters and Setters
    public String getId() { return id; }
    public void setId(String id) { this.id = id; }
    
    public String getFirstName() { return firstName; }
    public void setFirstName(String firstName) { this.firstName = firstName; }
    
    public String getLastName() { return lastName; }
    public void setLastName(String lastName) { this.lastName = lastName; }
    
    public String getDateOfBirth() { return dateOfBirth; }
    public void setDateOfBirth(String dateOfBirth) { this.dateOfBirth = dateOfBirth; }
    
    public String getSocialSecurityNumber() { return socialSecurityNumber; }
    public void setSocialSecurityNumber(String socialSecurityNumber) { this.socialSecurityNumber = socialSecurityNumber; }
    
    public String getEmail() { return email; }
    public void setEmail(String email) { this.email = email; }
    
    public String getPhoneNumber() { return phoneNumber; }
    public void setPhoneNumber(String phoneNumber) { this.phoneNumber = phoneNumber; }
    
    public String getAddress() { return address; }
    public void setAddress(String address) { this.address = address; }
    
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    
    @Override
    public LocalDateTime getPartitionColValue() { return createdAt; }

    @Override
    public void setPartitionColValue(LocalDateTime value) { this.createdAt = value; }

    
    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
    
    @Override
    public String toString() {
        return String.format("CitizenEntity{id='%s', name='%s %s', ssn='%s', status='%s', createdAt=%s}", 
            id, firstName, lastName, socialSecurityNumber, status, createdAt);
    }
}