package com.telcobright.splitverse.tests.entities;

import com.telcobright.core.annotation.*;
import com.telcobright.core.entity.ShardingEntity;
import java.time.LocalDateTime;

@Table(name = "audit_logs")
public class AuditLogEntity implements ShardingEntity<LocalDateTime> {

    @Id(autoGenerated = false)
    @Column(name = "id")
    private String id;

    @ShardingKey
    @Column(name = "event_time")
    private LocalDateTime eventTime;

    @Column(name = "user_id")
    private String userId;

    @Column(name = "action")
    private String action;

    @Column(name = "resource")
    private String resource;

    @Column(name = "ip_address")
    private String ipAddress;

    @Column(name = "details")
    private String details;

    // Default constructor
    public AuditLogEntity() {}

    // Constructor with parameters
    public AuditLogEntity(String id, String userId, String action, LocalDateTime eventTime) {
        this.id = id;
        this.userId = userId;
        this.action = action;
        this.eventTime = eventTime;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public LocalDateTime getPartitionColValue() {
        return eventTime;
    }

    @Override
    public void setPartitionColValue(LocalDateTime value) {
        this.eventTime = value;
    }

    // Getters and setters
    public LocalDateTime getEventTime() {
        return eventTime;
    }

    public void setEventTime(LocalDateTime eventTime) {
        this.eventTime = eventTime;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getAction() {
        return action;
    }

    public void setAction(String action) {
        this.action = action;
    }

    public String getResource() {
        return resource;
    }

    public void setResource(String resource) {
        this.resource = resource;
    }

    public String getIpAddress() {
        return ipAddress;
    }

    public void setIpAddress(String ipAddress) {
        this.ipAddress = ipAddress;
    }

    public String getDetails() {
        return details;
    }

    public void setDetails(String details) {
        this.details = details;
    }
}