package com.telcobright.splitverse.tests.entities;

import com.telcobright.core.annotation.*;
import com.telcobright.core.entity.ShardingEntity;
import java.time.LocalDateTime;

@Table(name = "users")
public class UserEntity implements ShardingEntity<LocalDateTime> {

    @Id(autoGenerated = false)
    @Column(name = "id")
    private String id;

    @ShardingKey
    @Column(name = "created_at")
    private LocalDateTime createdAt;

    @Column(name = "username")
    private String username;

    @Column(name = "email")
    private String email;

    @Column(name = "status")
    private String status;

    // Default constructor
    public UserEntity() {}

    // Constructor with parameters
    public UserEntity(String id, String username, String email, LocalDateTime createdAt) {
        this.id = id;
        this.username = username;
        this.email = email;
        this.createdAt = createdAt;
        this.status = "active";
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public LocalDateTime getPartitionColValue() {
        return createdAt;
    }

    @Override
    public void setPartitionColValue(LocalDateTime value) {
        this.createdAt = value;
    }

    // Getters and setters
    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
}